name: Docker Build and Publish

on:
  push:
    tags:
      - 'release-v*.*.*'  # 仅监听符合 release-v 前缀的标签推送

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract Version from Tag
        id: extract-version
        run: |
          # 从标签名中提取版本号（例如 release-v1.2.3 → 1.2.3）
          VERSION=${GITHUB_REF_NAME#release-v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Extract Repository Name
        id: extract-repo
        run: |
          # 提取仓库名称并转换为小写（符合 Docker 命名规则）
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.extract-repo.outputs.repo_name }}:${{ steps.extract-version.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.extract-repo.outputs.repo_name }}:latest
